import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, useLocation } from 'react-router-dom';
import {
    Box, Typography, Card, CardContent, Button, Alert, CircularProgress,
    Chip, Dialog, DialogTitle, DialogContent, DialogActions, Divider,
    TextField, ToggleButton, ToggleButtonGroup, Paper, Snackbar
} from '@mui/material';
import { Scorecard, DecisionCategory, ScoreValue, ScoreLevel } from '../types';
import { api } from '../api/client';
import { pillars, categories, emotions, getLevelLabel, getPillarFeedback, generateRuleBasedInsights, getVerdictFromTotal } from '../constants';
import { ScoreDisplay } from '../components/ScoreDisplay';

interface PillarState {
    score: ScoreValue | null;
    level: ScoreLevel | null;
    notes: string;
}

export const ScorecardDetail: React.FC = () => {
    const { id } = useParams<{ id: string }>();
    const navigate = useNavigate();
    const location = useLocation();
    const stateScorecard = (location.state as any)?.scorecard as Scorecard | undefined;

    const [scorecard, setScorecard] = useState<Scorecard | null>(stateScorecard || null);
    const [loading, setLoading] = useState(!stateScorecard);
    const [error, setError] = useState<string | null>(null);
    const [deleteOpen, setDeleteOpen] = useState(false);
    const [deleting, setDeleting] = useState(false);
    const [aiLoading, setAiLoading] = useState(false);

    // Outcome state
    const [showOutcomeForm, setShowOutcomeForm] = useState(false);
    const [outcomeResult, setOutcomeResult] = useState<string>('neutral');
    const [outcomeNotes, setOutcomeNotes] = useState('');
    const [outcomeSaving, setOutcomeSaving] = useState(false);

    // Edit state
    const [editing, setEditing] = useState(false);
    const [editTitle, setEditTitle] = useState('');
    const [editCategory, setEditCategory] = useState('');
    const [editIsPreDecision, setEditIsPreDecision] = useState(true);
    const [editScores, setEditScores] = useState<Record<string, PillarState>>({});
    const [editSaving, setEditSaving] = useState(false);
    const [copied, setCopied] = useState(false);

    const handleShareSummary = () => {
        if (!scorecard) return;
        const verdict = getVerdictFromTotal(scorecard.totalScore);
        const cat = categories.find(c => c.value === scorecard.category);
        const pillarSummary = scorecard.scores.map(s => {
            const levelInfo = s.level ? getLevelLabel(s.level) : null;
            return `  ${levelInfo?.icon || '•'} ${s.pillarName}: ${levelInfo?.label || 'N/A'}`;
        }).join('\n');

        const summary = [
            `📋 Decision Audit: ${scorecard.title}`,
            `📁 Category: ${cat?.icon || ''} ${cat?.label || scorecard.category}`,
            `📊 Score: ${scorecard.totalScore > 0 ? '+' : ''}${scorecard.totalScore} — ${verdict.icon} ${verdict.label}`,
            ``,
            `Pillar Breakdown:`,
            pillarSummary,
            ``,
            `💡 ${verdict.recommendation}`,
            scorecard.outcome ? `\n📋 Outcome: ${scorecard.outcome.result}${scorecard.outcome.notes ? ' — ' + scorecard.outcome.notes : ''}` : '',
            ``,
            `— Generated by Universal Decision Audit Scorecard`
        ].filter(Boolean).join('\n');

        navigator.clipboard.writeText(summary).then(() => setCopied(true));
    };

    useEffect(() => {
        if (!stateScorecard && id) {
            loadScorecard();
        }
    }, [id]);

    const loadScorecard = async () => {
        try {
            const data = await api.getScorecard(id!);
            setScorecard(data);
        } catch (err: any) {
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    const handleDelete = async () => {
        setDeleting(true);
        try {
            await api.deleteScorecard(id!);
            navigate('/');
        } catch (err: any) {
            setError(err.message);
            setDeleting(false);
            setDeleteOpen(false);
        }
    };

    const handleGetInsights = async () => {
        if (!scorecard) return;
        setAiLoading(true);
        try {
            const result = await api.getAiInsights(scorecard.id, scorecard);
            setScorecard({ ...scorecard, aiInsights: result.insights });
        } catch (err: any) {
            setError(err.message);
        } finally {
            setAiLoading(false);
        }
    };

    const handleSaveOutcome = async () => {
        if (!scorecard) return;
        setOutcomeSaving(true);
        setError(null);
        try {
            const updated = await api.updateOutcome(scorecard.id, {
                result: outcomeResult,
                notes: outcomeNotes
            });
            setScorecard(updated);
            setShowOutcomeForm(false);
        } catch (err: any) {
            setError(err.message);
        } finally {
            setOutcomeSaving(false);
        }
    };

    const startEditing = () => {
        if (!scorecard) return;
        setEditTitle(scorecard.title);
        setEditCategory(scorecard.category);
        setEditIsPreDecision(scorecard.isPreDecision);
        const scoreLookup: Record<string, PillarState> = {};
        for (const pillar of pillars) {
            const existing = scorecard.scores.find(s => s.pillarId === pillar.id);
            scoreLookup[pillar.id] = {
                score: (existing?.score ?? null) as ScoreValue | null,
                level: (existing?.level ?? null) as ScoreLevel | null,
                notes: existing?.notes || ''
            };
        }
        setEditScores(scoreLookup);
        setEditing(true);
    };

    const handleSaveEdit = async () => {
        if (!scorecard) return;
        setEditSaving(true);
        setError(null);
        try {
            const data = {
                category: editCategory,
                title: editTitle,
                isPreDecision: editIsPreDecision,
                emotionBefore: scorecard.emotionBefore,
                scores: Object.entries(editScores).map(([pillarId, d]) => ({
                    pillarId,
                    pillarName: pillars.find(p => p.id === pillarId)?.name || pillarId,
                    score: d.score,
                    level: d.level,
                    notes: d.notes
                }))
            };
            const updated = await api.updateScorecard(scorecard.id, data);
            setScorecard(updated);
            setEditing(false);
        } catch (err: any) {
            setError(err.message);
        } finally {
            setEditSaving(false);
        }
    };

    if (loading) {
        return <Box sx={{ textAlign: 'center', py: 8 }}><CircularProgress /></Box>;
    }

    if (error && !scorecard) {
        return (
            <Box>
                <Button onClick={() => navigate('/')} sx={{ mb: 2 }}>← Back to Dashboard</Button>
                <Alert severity="error">{error}</Alert>
            </Box>
        );
    }

    if (!scorecard) {
        return (
            <Box>
                <Button onClick={() => navigate('/')} sx={{ mb: 2 }}>← Back to Dashboard</Button>
                <Alert severity="warning">Scorecard not found</Alert>
            </Box>
        );
    }

    const cat = categories.find(c => c.value === scorecard.category);

    const outcomeLabels: Record<string, { icon: string; label: string; color: string }> = {
        positive: { icon: '✅', label: 'Positive', color: '#10B981' },
        neutral: { icon: '➖', label: 'Neutral', color: '#F59E0B' },
        negative: { icon: '❌', label: 'Negative', color: '#EF4444' }
    };

    if (editing) {
        const allEditScored = Object.values(editScores).every(s => s.score !== null);
        return (
            <Box>
                <Button onClick={() => setEditing(false)} sx={{ mb: 2 }}>← Cancel Editing</Button>
                <Typography variant="h5" fontWeight={700} gutterBottom>Edit Scorecard</Typography>

                <Card sx={{ mb: 3 }}>
                    <CardContent>
                        <TextField
                            fullWidth label="Decision Title" value={editTitle}
                            onChange={e => setEditTitle(e.target.value)} sx={{ mb: 2 }}
                        />
                        <Box sx={{
                            display: 'grid',
                            gridTemplateColumns: { xs: 'repeat(2, 1fr)', sm: 'repeat(3, 1fr)' },
                            gap: 1.5, mb: 2
                        }}>
                            {categories.map(c => (
                                <Paper
                                    key={c.value} elevation={editCategory === c.value ? 4 : 0}
                                    onClick={() => setEditCategory(c.value)}
                                    sx={{
                                        p: 1.5, textAlign: 'center', cursor: 'pointer',
                                        border: editCategory === c.value ? `2px solid ${c.color}` : '2px solid transparent',
                                        bgcolor: editCategory === c.value ? `${c.color}15` : 'background.paper',
                                        transition: 'all 0.2s'
                                    }}
                                >
                                    <Typography variant="body1">{c.icon}</Typography>
                                    <Typography variant="caption" fontWeight={600}>{c.label}</Typography>
                                </Paper>
                            ))}
                        </Box>
                        <ToggleButtonGroup
                            value={editIsPreDecision ? 'pre' : 'post'} exclusive
                            onChange={(_, v) => v && setEditIsPreDecision(v === 'pre')}
                            fullWidth size="small"
                        >
                            <ToggleButton value="pre">🔮 Pre-decision</ToggleButton>
                            <ToggleButton value="post">🔍 Post-decision</ToggleButton>
                        </ToggleButtonGroup>
                    </CardContent>
                </Card>

                {pillars.map(pillar => {
                    const currentState = editScores[pillar.id];
                    const question = editIsPreDecision ? pillar.preQuestion : pillar.postQuestion;
                    return (
                        <Card key={pillar.id} sx={{ mb: 2 }}>
                            <CardContent>
                                <Typography variant="subtitle1" fontWeight={600}>{pillar.name}</Typography>
                                <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>{question}</Typography>
                                <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1, mb: 1 }}>
                                    {pillar.options.map(option => {
                                        const isSelected = currentState?.level === option.level;
                                        const levelInfo = getLevelLabel(option.level);
                                        return (
                                            <Paper
                                                key={option.level}
                                                onClick={() => setEditScores(prev => ({
                                                    ...prev,
                                                    [pillar.id]: { ...prev[pillar.id], score: option.value, level: option.level }
                                                }))}
                                                elevation={isSelected ? 3 : 0}
                                                sx={{
                                                    p: 2, cursor: 'pointer',
                                                    border: isSelected ? `2px solid ${levelInfo.color}` : '2px solid #E4E4E7',
                                                    bgcolor: isSelected ? `${levelInfo.color}10` : 'background.paper',
                                                    transition: 'all 0.2s',
                                                    '&:hover': { borderColor: levelInfo.color }
                                                }}
                                            >
                                                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                                                    <Typography variant="body1">{option.icon}</Typography>
                                                    <Typography variant="body2" fontWeight={600}>{option.label}</Typography>
                                                </Box>
                                            </Paper>
                                        );
                                    })}
                                </Box>
                                <TextField
                                    fullWidth multiline rows={2} size="small" label="Notes (optional)"
                                    value={editScores[pillar.id]?.notes || ''}
                                    onChange={e => setEditScores(prev => ({
                                        ...prev,
                                        [pillar.id]: { ...prev[pillar.id], notes: e.target.value }
                                    }))}
                                    sx={{ mt: 1 }}
                                />
                            </CardContent>
                        </Card>
                    );
                })}

                {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}

                <Box sx={{ display: 'flex', gap: 2 }}>
                    <Button onClick={() => setEditing(false)}>Cancel</Button>
                    <Button
                        variant="contained" onClick={handleSaveEdit}
                        disabled={editSaving || !allEditScored || !editTitle.trim() || !editCategory}
                        fullWidth size="large"
                    >
                        {editSaving ? 'Saving...' : 'Save Changes'}
                    </Button>
                </Box>
            </Box>
        );
    }

    return (
        <Box sx={{ animation: 'fadeInUp 0.4s ease' }}>
            <Button onClick={() => navigate('/')} sx={{ mb: 2 }}>← Back to Dashboard</Button>

            <ScoreDisplay totalScore={scorecard.totalScore} />

            <Card sx={{ mb: 3 }}>
                <CardContent>
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 2 }}>
                        <Box>
                            <Typography variant="h5" fontWeight={700}>{scorecard.title}</Typography>
                            <Box sx={{ display: 'flex', gap: 1, mt: 1 }}>
                                <Chip
                                    label={`${cat?.icon} ${cat?.label}`}
                                    sx={{ bgcolor: cat?.color, color: 'white' }}
                                />
                                <Chip
                                    label={scorecard.isPreDecision ? '🔮 Pre-decision' : '🔍 Post-decision'}
                                    variant="outlined"
                                />
                            </Box>
                        </Box>
                        <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
                            <Typography variant="body2" color="text.secondary">
                                {new Date(scorecard.createdAt).toLocaleDateString()}
                            </Typography>
                            <Button variant="outlined" size="small" onClick={handleShareSummary}>
                                📤 Share
                            </Button>
                            <Button variant="outlined" size="small" onClick={startEditing}>
                                ✏️ Edit
                            </Button>
                        </Box>
                    </Box>

                    <Divider sx={{ my: 2 }} />

                    <Typography variant="subtitle2" gutterBottom>Pillar Breakdown</Typography>
                    {scorecard.scores.map(s => {
                        const levelInfo = s.level ? getLevelLabel(s.level) : null;
                        const feedback = s.level ? getPillarFeedback(s.pillarId, s.pillarName, s.level) : null;

                        return (
                            <Box key={s.pillarId} sx={{ mb: 2, p: 2, bgcolor: '#f5f7fa', borderRadius: 1 }}>
                                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                    <Typography variant="body2" fontWeight={600}>
                                        {s.pillarName}
                                    </Typography>
                                    {levelInfo && (
                                        <Chip
                                            label={`${levelInfo.icon} ${levelInfo.label}`}
                                            size="small"
                                            sx={{ bgcolor: `${levelInfo.color}20`, color: levelInfo.color, fontWeight: 600 }}
                                        />
                                    )}
                                </Box>
                                {feedback && (
                                    <Box sx={{ mt: 1 }}>
                                        <Typography variant="body2" color="text.secondary" sx={{ mb: 0.5 }}>
                                            {feedback.feedback}
                                        </Typography>
                                        {s.level !== 'good' && (
                                            <Typography variant="body2" sx={{ color: '#6366F1', fontWeight: 500 }}>
                                                → {feedback.actionItem}
                                            </Typography>
                                        )}
                                    </Box>
                                )}
                                {s.notes && (
                                    <Typography variant="body2" sx={{ mt: 1, fontStyle: 'italic' }}>
                                        &ldquo;{s.notes}&rdquo;
                                    </Typography>
                                )}
                            </Box>
                        );
                    })}

                    {scorecard.emotionBefore && scorecard.emotionBefore.emotions.length > 0 && (
                        <>
                            <Divider sx={{ my: 2 }} />
                            <Typography variant="subtitle2" gutterBottom>Emotional State</Typography>
                            <Box sx={{ p: 2, bgcolor: '#f0f0ff', borderRadius: 1 }}>
                                <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap', mb: 1 }}>
                                    {scorecard.emotionBefore.emotions.map(eid => {
                                        const em = emotions.find(e => e.id === eid);
                                        return em ? (
                                            <Chip key={eid} label={`${em.icon} ${em.label}`} size="small" variant="outlined" />
                                        ) : null;
                                    })}
                                </Box>
                                <Typography variant="caption" color="text.secondary">
                                    Intensity: {scorecard.emotionBefore.intensity}/10
                                </Typography>
                            </Box>
                        </>
                    )}
                </CardContent>
            </Card>

            {/* Outcome Tracking */}
            <Card sx={{ mb: 3, bgcolor: scorecard.outcome ? '#f0fdf4' : '#fffbeb', border: `1px solid ${scorecard.outcome ? '#10B98130' : '#F59E0B30'}` }}>
                <CardContent>
                    <Typography variant="subtitle2" fontWeight={600} gutterBottom>
                        📋 Decision Outcome
                    </Typography>
                    {scorecard.outcome ? (
                        <Box>
                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
                                <Chip
                                    label={`${outcomeLabels[scorecard.outcome.result]?.icon} ${outcomeLabels[scorecard.outcome.result]?.label}`}
                                    sx={{
                                        bgcolor: `${outcomeLabels[scorecard.outcome.result]?.color}20`,
                                        color: outcomeLabels[scorecard.outcome.result]?.color,
                                        fontWeight: 600
                                    }}
                                />
                                <Typography variant="caption" color="text.secondary">
                                    Recorded {new Date(scorecard.outcome.recordedAt).toLocaleDateString()}
                                </Typography>
                            </Box>
                            {scorecard.outcome.notes && (
                                <Typography variant="body2" sx={{ mt: 1, fontStyle: 'italic' }}>
                                    &ldquo;{scorecard.outcome.notes}&rdquo;
                                </Typography>
                            )}
                            {scorecard.outcome.result === 'negative' && scorecard.totalScore >= 2 && (
                                <Alert severity="info" sx={{ mt: 2 }}>
                                    Your audit scored well but the outcome was negative — external factors may have played a role, or consider whether scores were too generous.
                                </Alert>
                            )}
                            {scorecard.outcome.result === 'positive' && scorecard.totalScore <= -1 && (
                                <Alert severity="info" sx={{ mt: 2 }}>
                                    Positive outcome despite low scores — you may have gotten lucky. Don't let this reinforce poor process.
                                </Alert>
                            )}
                        </Box>
                    ) : showOutcomeForm ? (
                        <Box>
                            <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                                How did this decision turn out?
                            </Typography>
                            <ToggleButtonGroup
                                value={outcomeResult} exclusive
                                onChange={(_, v) => v && setOutcomeResult(v)}
                                fullWidth sx={{ mb: 2 }}
                            >
                                <ToggleButton value="positive" sx={{ color: '#10B981' }}>✅ Positive</ToggleButton>
                                <ToggleButton value="neutral" sx={{ color: '#F59E0B' }}>➖ Neutral</ToggleButton>
                                <ToggleButton value="negative" sx={{ color: '#EF4444' }}>❌ Negative</ToggleButton>
                            </ToggleButtonGroup>
                            <TextField
                                fullWidth multiline rows={3} label="What happened? (optional)"
                                value={outcomeNotes} onChange={e => setOutcomeNotes(e.target.value)}
                                sx={{ mb: 2 }}
                            />
                            <Box sx={{ display: 'flex', gap: 2 }}>
                                <Button onClick={() => setShowOutcomeForm(false)}>Cancel</Button>
                                <Button variant="contained" onClick={handleSaveOutcome} disabled={outcomeSaving} fullWidth>
                                    {outcomeSaving ? 'Saving...' : 'Save Outcome'}
                                </Button>
                            </Box>
                        </Box>
                    ) : (
                        <Box>
                            <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                                Track what actually happened to validate your decision-making process.
                            </Typography>
                            <Button variant="outlined" onClick={() => setShowOutcomeForm(true)}>
                                Record Outcome
                            </Button>
                        </Box>
                    )}
                </CardContent>
            </Card>

            <Card sx={{ mb: 3, bgcolor: '#f0f7ff' }}>
                <CardContent>
                    <Typography variant="subtitle2" fontWeight={600} gutterBottom>💡 Decision Insights</Typography>
                    {(() => {
                        const ruleInsights = scorecard.ruleInsights || generateRuleBasedInsights(
                            scorecard.scores,
                            scorecard.category as DecisionCategory,
                            scorecard.emotionBefore,
                            scorecard.isPreDecision
                        );
                        return ruleInsights.map((insight, i) => (
                            <Box key={i} sx={{ mb: 1.5, p: 1.5, bgcolor: 'white', borderRadius: 1, border: '1px solid #E4E4E7' }}>
                                <Typography variant="body2">{insight}</Typography>
                            </Box>
                        ));
                    })()}
                </CardContent>
            </Card>

            <Card sx={{ mb: 3, bgcolor: scorecard.aiInsights ? '#f5f0ff' : undefined }}>
                <CardContent>
                    <Typography variant="subtitle2" fontWeight={600} gutterBottom>🤖 AI-Powered Insights</Typography>
                    {scorecard.aiInsights ? (
                        <Typography variant="body2" sx={{ whiteSpace: 'pre-line' }}>
                            {scorecard.aiInsights}
                        </Typography>
                    ) : (
                        <Box>
                            <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                                Get deeper, personalized analysis powered by AI.
                            </Typography>
                            <Button
                                variant="outlined"
                                onClick={handleGetInsights}
                                disabled={aiLoading}
                            >
                                {aiLoading ? 'Generating...' : 'Generate AI Analysis'}
                            </Button>
                        </Box>
                    )}
                </CardContent>
            </Card>

            {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}

            <Button color="error" variant="outlined" onClick={() => setDeleteOpen(true)}>
                Delete Scorecard
            </Button>

            <Dialog open={deleteOpen} onClose={() => setDeleteOpen(false)}>
                <DialogTitle>Delete Scorecard?</DialogTitle>
                <DialogContent>
                    <Typography>This action cannot be undone.</Typography>
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => setDeleteOpen(false)}>Cancel</Button>
                    <Button color="error" onClick={handleDelete} disabled={deleting}>
                        {deleting ? 'Deleting...' : 'Delete'}
                    </Button>
                </DialogActions>
            </Dialog>

            <Snackbar
                open={copied}
                autoHideDuration={3000}
                onClose={() => setCopied(false)}
                message="✓ Summary copied to clipboard"
            />
        </Box>
    );
};
